input: "../demo/input"
results: "../demo/results"
local_crs: 32735
country: "tza"
admin_level: "01"
bbox: [39.01, 41, -7.19, -6.57] #Â dar es salaam [west, east, south, north]
asset_geoms:
  - "tza_roads_bridges_and_culverts_nodes"
  - "tza_railway_edges"
  - "tza_airports_polygons"
hazards:
  - "cyclone"